### ISSUE TITLE
Сделать страничку профиля

### ISSUE THREAD

**Issue by orby-tech** [roll-over/unknown-interview#26]
1) Информация по резюме
2) Подходящая рандомная вакансия
3) кнопки: Лайк, пропустить дизлайк

**Comment by HugeLetters** [comment]
Можно линк на фрейм в макете?

**Comment by orby-tech** [comment]
Воть https://www.figma.com/file/Aiv1GFLtbGJjIOZJqSYKsp/%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82?type=design&node-id=184-195&mode=design&t=WAyuvO8k4EK23j8a-0
