### ISSUE TITLE
Сделать мульти селект skills

### ISSUE THREAD

**Issue by orby-tech** [roll-over/unknown-interview#54]
Думаю лучше всего будет сделать чипсами

На страницах:
- [ ] Employess search
- [ ] Job search
- [ ] Depends on #55 
- [ ] Depends on #56 
- [ ] Depends on #6 
- [ ] Depends on #7 

Вот тут макет для представления чипс https://www.figma.com/file/Aiv1GFLtbGJjIOZJqSYKsp/%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82?type=design&node-id=85-192&mode=design&t=OiEyuLNDO6sX3ebv-0

**Comment by HugeLetters** [comment]
Уже сделано
