### ISSUE TITLE
Сверстать рабочую панель hr

### ISSUE THREAD

**Issue by orby-tech** [roll-over/unknown-interview#71]
- Информация по вакансии
- Подходящее рандомное резюме
- кнопки: Лайк, пропустить дизлайк

**Comment by HugeLetters** [comment]
Можно линк на фрейм в макете?

**Comment by orby-tech** [comment]
https://www.figma.com/file/Aiv1GFLtbGJjIOZJqSYKsp/%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82?type=design&node-id=384-953&mode=design&t=WAyuvO8k4EK23j8a-0
